version: '3'

services:
  backend:
    restart: always
    container_name: olok-backend
    build:
      context: ./BackEnd/backend/
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      olok-net-frontend:
        ipv4_address: 10.0.0.3
      olok-net-backend:
        ipv4_address: 10.0.1.3


networks:
  olok-net-frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  olok-net-backend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24