version: '3'

services:
  frontend:
    restart: always
    env_file:
      - ./front.env
    container_name: olok-frontend
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./FrontEnd/:/usr/local/app
    ports:
      - "80:4200"
    networks:
      olok-net-frontend:
        ipv4_address: 10.0.0.2

  backend:
    restart: always
    container_name: olok-backend
    build:
      context: ./BackEnd/backend/
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      olok-net-frontend:
        ipv4_address: 10.0.0.3
      olok-net-backend:
        ipv4_address: 10.0.1.3
    depends_on:
      - db-nosql
      - db-sql

  db-nosql:
    restart: always
    container_name: db-nosql
    env_file:
      - ./db_nosql.env 
    volumes:
      - ./db_nosql/db:/data/db
    build:
      context: ./db_nosql
      dockerfile: Dockerfile
    networks:
      olok-net-backend:
        ipv4_address: 10.0.1.4
    ports:
      - "27017:27017"

  db-sql:
    restart: always
    container_name: db-sql
    env_file:
      - ./db_sql.env
    volumes:
      - ./db_sql/db:/var/lib/postgresql/data
    build:
      context: ./db_sql
      dockerfile: Dockerfile
    healthcheck:
      test: pg_isready -U olok
      interval: 1m
      timeout: 10s
      retries: 2
    ports:
      - "5432:5432"
    networks:
      olok-net-backend:
        ipv4_address: 10.0.1.5

  log-analysis:
    restart: always
    container_name: log-analysis
    build:
      context: ./BackEnd/logAnalysis/
      dockerfile: Dockerfile
    volumes:
      - ./BackEnd/logAnalysis/logs:/app/logs:rw
      - ./BackEnd/logAnalysis/models:/app/models:rw
      - ./BackEnd/logAnalysis/tmp:/app/tmp:rw
    networks:
      olok-net-backend:
        ipv4_address: 10.0.1.6
    ports:
      - "54321:54321"
    depends_on:
      - backend

  maildev:
    restart: always
    container_name: maildev
    image: maildev/maildev
    networks:
      olok-net-backend:
        ipv4_address: 10.0.1.7
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  olok-net-frontend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  olok-net-backend:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24